### ISSUE TITLE
Can't install plugin I get the following error

### ISSUE THREAD

**Issue by summercms** [LukeTowers/oc-easyfacebookfeed-plugin#2]
@LukeTowers 

Hi Luke , happy new year.

I get the following error message when trying to install your plugin:

> Version file /home/www/example/public_html/plugins/luketowers/easyfacebookfeed/updates/Fixed bug where pinning items that were included in the regular feed would count against the total number of items that could be displayed in the feed.php is not found.

Forgot to say I'm running php7.3

**Comment by LukeTowers** [comment]
@ayumi-cloud are you using the latest version of October? Multi line comments in version files were added recently and this plugin uses them:

```yaml
1.0.1:
    - 'First version of EasyFacebookFeed'
    - create_feeds_table.php
    - create_feed_items_table.php
1.0.2:
    - 'Improved handling of invalid data from Facebook'
1.0.3:
    - 'Added ability to choose whether to fully sync a feed on creation or just the most recent 100 posts'
1.0.4:
    - 'Updated links to FindMyFBID in the setup instructions'
1.0.5:
    - 'Removed dependency on Font Awesome from the default styling'
    - 'Fixed bug where pinning items that were included in the regular feed would count against the total number of items that could be displayed in the feed'
```

**Comment by summercms** [comment]
@LukeTowers 

That's weird it sorted itself out and install itself as well...?

Nevermind, will close this issue, this new test server is acting strange?
